name: Analysis
on:
  pull_request:
jobs:
  check:
    name: pre-merge-checks
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Setup Haskell
        id: setup-haskell-cabal
        uses: haskell/actions/setup@v1
        with:
          ghc-version: 8.10

      - name: Cabal Check
        run: cabal check

      - name: Lint
        run: curl -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
